DROP DATABASE IF EXISTS EmpleadosTEIS;
  CREATE DATABASE   EmpleadosTEIS
    CHARACTER =   utf32 
    COLLATE         utf32_spanish2_ci;

USE           EnviosTEIS;


DROP TABLE IF EXISTS CONTRIBUCION;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS CARGAFAMILIAR;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS PROYECTO;
DROP TABLE IF EXISTS TIENE;
DROP TABLE IF EXISTS REALIZA;
DROP TABLE IF EXISTS PERTENECE;
DROP TABLE IF EXISTS DIRIGE;
DROP TABLE IF EXISTS TRABAJA;

CREATE TABLE TRABAJA(
  idProyecto  INT,
  idEmpleado  INT,
  fechaContratacion DATE

);
CREATE TABLE DIRIGE(
  idDepartamento  INT,
  idEmpleado    INT,
  inicioDireccion   DATE

);
CREATE TABLE PERTENECE(
idEmpleado  INT,
idDepartamento  INT,
fechaContratacion   DATE,
cargo           VARCHAR(30)
);

CREATE TABLE REALIZA(
idProyecto  INT,
idEmpleado  INT,
fechaContratacion DATE

);
CREATE TABLE TIENE(
idProyecto  INT,
idEmpleado  INT,
parentesco  VARCHAR(30)
);

CREATE TABLE PROYECTO(


);
CREATE TABLE DEPARTAMENTO();
CREATE TABLE CARGAFAMILIAR();
CREATE TABLE EMPLEADO();
CREATE TABLE CONTRIBUCION();

