SELECT * FROM PRODUCTO ORDER BY PRECIO DESC;
SELECT * FROM PRODUCTO ORDER BY PRECIO DESC OFFSET 0 ROWS FETCH NEXT 2 ROW ONLY;
SELECT MAX(Precio) FROM PRODUCTO;

SELECT * FROM PRODUCTO WHERE Precio = ( SELECT MAX( Precio ) FROM PRODUCTO );
SELECT * FROM PRODUCTO WHERE Precio IN ( SELECT MAX ( Precio ) FROM PRODUCTO );
SELECT * FROM PRODUCTO WHERE Precio >= ALL ( SELECT MAX ( Precio ) FROM PRODUCTO );

SELECT * FROM PRODUCTO WHERE Precio = (SELECT MAX( Precio ) FROM PRODUCTO);
SELECT * FROM PRODUCTO WHERE Precio IN ( SELECT MAX( Precio ) FROM PRODUCTO);
SELECT * FROM PRODUCTO WHERE Precio != SOME ( SELECT Precio FROM PRODUCTO);

SELECT * FROM PRODUCTO WHERE Precio > ( SELECT SUM( Precio )/COUNT(*) FROM PRODUCTO);
SELECT AVG( Precio ) FROM PRODUCTO;
-- Obtenemos la varianza y la desviación típica.
-- (Sumatorio de (Media - valor)^2) /  numero de elementos
SELECT Nombre, Precio, ( SELECT AVG( Precio ) FROM PRODUCTO ) AS PrecioMedio, 
(Precio - ( SELECT AVG(PRECIO) FROM PRODUCTO)) AS DIFERENCIA FROM PRODUCTO;

CREATE OR REPLACE VIEW VALOR_MEDIO AS (SELECT AVG(PRECIO) AS VM FROM PRODUCTO);
SELECT Nombre, Precio, (SELECT * FROM VALOR_MEDIO),
    (Precio - (SELECT * FROM VALOR_MEDIO) AS Diferencia FROM PRODUCTO);

SELECT * FROM DETALLES;
CREATE OR REPLACE VIEW Vista_Detalles AS (SELECT ID_Producto, CantComprada FROM Detalles);
SELECT * FROM Vista_Detalles;

SELECT * FROM ENVIO;
CREATE OR REPLACE VIEW Vista_Envios AS (SELECT ID_Envio, Estado FROM Envio);
SELECT * FROM Vista_Envios;
SELECT * FROM Envio WHERE ID_Envio IN ( SELECT ID_ENVIO WHERE ESTADO IN ( 'Enviado' ) );

CREATE OR REPLACE VIEW Producto_Admin_Menores AS SELECT * FROM PRODUCTO WHERE ID_ADMIN < 6;
CREATE OR REPLACE VIEW Producto_Admin_Mayores AS SELECT * FROM PRODUCTO WHERE ID_ADMIN >=5;
SELECT * FROM Producto_Admin_Menores;
SELECT * FROM Producto_Admin_Mayores;

DELETE FROM Producto_Admin_Menores;